version: '3.7'

services:
    backend:
        container_name: "backend"
        build:
            context: .
            dockerfile: ./docker/server/Dockerfile
        expose:
            - "9000"
            - "9003"
        ports:
            - "9898:80"
        working_dir: /var/www/html
        volumes:
            - ./backend:/var/www/html
            - ./docker/server/apache/sites-enabled:/etc/apache2/sites-enabled
            - ./docker/server/php/php.ini:/usr/local/etc/php/conf.d/extra-php-config.ini
            - ./docker/xdebug/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
        depends_on:
            - database
        networks:
            - inner_net
    
    database:
        container_name: "database_server"
        healthcheck:
            test: mysqladmin ping -h 127.0.0.1 -u root --password=$$MYSQL_ROOT_PASSWORD
            interval: 5s
            retries: 5
        image: mysql
        volumes:
            - db_data:/var/lib/mysql
            - ./docker/db/mariadb/my.cnf:/etc/mysql/conf.d/my.cnf
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: 'superSecr3t'
            MYSQL_USER: 'app_user'
            MYSQL_PASSWORD: 't3rceS'
            MYSQL_DATABASE: 'database'
        networks:
            - inner_net
    
    myadmin:
        container_name: "phpmyadmin"
        image: phpmyadmin/phpmyadmin:5
        environment:
            PMA_HOST: database
        ports:
            - "8080:80"
        depends_on:
            - database
        networks:
            - inner_net
        volumes:
            - db_admin_data:/var/www/html
    

    frontend:
        container_name: "frontend"
        build:
            context: .
            dockerfile: ./docker/front/Dockerfile
        volumes:
            - ./frontend:/app
        ports:
            - "3000:3000"
        networks:
            - inner_net
        depends_on:
            - backend

volumes:
    db_data:
    db_admin_data:

networks:
    inner_net:
